env:
  global:
    - CC_TEST_REPORTER_ID=04d15658ddb06b731dd4b879b55a0a3c65e9a17989850a0c41cdec8e09503dce

language: python
python:
  # we want to test our package on several versions of Python
  - 3.6
  - 3.7
  - 3.8

before_install:
  # make depends on poetry
  - pip install poetry

install:
  - make install

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - make check

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
